# Generated by Django 3.2.2 on 2021-05-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pressure', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('BBCtemperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('BBCpressure', models.DecimalField(decimal_places=1, max_digits=4)),
                ('BBChumidity', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
